### ISSUE TITLE
flight (d) false

### ISSUE THREAD

**Issue by coolpvpv1** [crumbedcutlets/Storm-Anticheat#8]
if your in a cobweb up like 6 blocks in the air then when you go through like half of it when your kinda getting to the end of it you get flagged down for flight (d)

**Comment by crumbedcutlets** [comment]
I can't help without more info like
Server:
Anticheat Version:

**Comment by coolpvpv1** [comment]
> I can't help without more info like
> Server:
> Anticheat Version:

server version is 1.8.8 and anticheat version is the newest one

**Comment by coolpvpv1** [comment]
> I can't help without more info like
> Server:
> Anticheat Version:

here a video https://streamable.com/otu8n

**Comment by crumbedcutlets** [comment]
Thanks
